baseURL = "https://adampisula.pizza"
languageCode = 'en-us'
title= "Adam Pisula | Software Developer"
theme = 'hello-friend'
paginate = 5

googleAnalytics = "G-F5VNBX8G2Q"

[params]
	defaultTheme = "dark"
	showReadingTime = true
	toc = true

[params.logo]
	logoHomeLink = "/"
	logoText = "Adam Pisula"

[sitemap]
	changefreq = 'weekly'
  priority = 1

# [menu]
# 	[[menu.main]]
# 		identifier = "about"
# 		name = "About"
# 		url = "/about"

# 	[[menu.main]]
# 		identifier = "projects"
# 		name = "Projects"
# 		url = "/projects"

