events {}
http {
    include mime.types;
    sendfile on;

    server {
        listen 80;
        listen [::]:80;

        resolver 0.0.0.0;
        autoindex off;

        server_name _;
        server_tokens off;

        root /app/dist;
        gzip_static on;
    }
}